services:
  cv-dev:
    image: ghcr.io/typst/typst:latest
    volumes:
      - ..:/workspace
      - ../fonts:/usr/share/fonts/custom
    working_dir: /workspace
    entrypoint: ["sleep", "infinity"]

  cv-build:
    image: ghcr.io/typst/typst:latest
    volumes:
      - ..:/workspace
      - ../fonts:/usr/share/fonts/custom
    working_dir: /workspace



